"""empty message

Revision ID: 0ab9016b9804
Revises: 
Create Date: 2019-04-17 20:39:43.771971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab9016b9804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming', sa.Column('_fractional_number_for_realiz', sa.Integer(), nullable=True))
    op.add_column('incoming', sa.Column('quantity_for_realiz', sa.Integer(), nullable=True))
    op.alter_column('incoming', '_cost_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('incoming', '_persent',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('incoming', '_purchase_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'])
    op.alter_column('incoming', '_purchase_cost',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('incoming', '_persent',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('incoming', '_cost_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('incoming', 'quantity_for_realiz')
    op.drop_column('incoming', '_fractional_number_for_realiz')
    # ### end Alembic commands ###
