"""empty message

Revision ID: 276df78a6aa4
Revises: 9c759e2ba8cb
Create Date: 2019-04-17 21:29:14.250146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276df78a6aa4'
down_revision = '9c759e2ba8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incoming', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'docIncomin', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incoming', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'docIncomin', ['parent_id'], ['id'])

    # ### end Alembic commands ###
