"""empty message

Revision ID: 51ee3dac4b0f
Revises: 0ab9016b9804
Create Date: 2019-04-17 20:47:47.104714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ee3dac4b0f'
down_revision = '0ab9016b9804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming', '_cost_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('incoming', '_persent',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('incoming', '_purchase_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'])
    op.alter_column('incoming', '_purchase_cost',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('incoming', '_persent',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('incoming', '_cost_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
