"""empty message

Revision ID: b3eabf0c2c97
Revises: f6cc21ef52ed
Create Date: 2019-04-17 21:10:27.208577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3eabf0c2c97'
down_revision = 'f6cc21ef52ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docIncomin', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'])
    op.drop_column('docIncomin', 'status')
    # ### end Alembic commands ###
