"""empty message

Revision ID: d1cefbb64dd4
Revises: b3eabf0c2c97
Create Date: 2019-04-17 21:10:58.573353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cefbb64dd4'
down_revision = 'b3eabf0c2c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'])
    # ### end Alembic commands ###
