"""empty message

Revision ID: efaa09c251eb
Revises: 276df78a6aa4
Create Date: 2019-05-12 03:26:47.726003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaa09c251eb'
down_revision = '276df78a6aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docIncomin', schema=None) as batch_op:
        pass
        # batch_op.add_column(sa.Column('DOC_NAME', sa.String(), nullable=True))
        # batch_op.add_column(sa.Column('PRICE_ALL_SUM', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('QUANT_NUM', sa.Integer(), nullable=True))

    with op.batch_alter_table('voucherelem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'voucher', ['ID_VOUCHER'], ['id'])
        batch_op.create_foreign_key(None, 'incoming', ['ID_PARCEL'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucherelem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'voucherelem', ['ID_VOUCHER'], ['id'])
        batch_op.create_foreign_key(None, 'voucherelem', ['ID_PARCEL'], ['id'])

    with op.batch_alter_table('docIncomin', schema=None) as batch_op:
        batch_op.drop_column('QUANT_NUM')
        batch_op.drop_column('PRICE_ALL_SUM')
        batch_op.drop_column('DOC_NAME')

    # ### end Alembic commands ###
