"""empty message

Revision ID: f6cc21ef52ed
Revises: 51ee3dac4b0f
Create Date: 2019-04-17 21:00:28.705057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cc21ef52ed'
down_revision = '51ee3dac4b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming', '_cost_price',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('incoming', '_persent',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('incoming', '_purchase_cost',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incoming', type_='foreignkey')
    op.create_foreign_key(None, 'incoming', 'docIncomin', ['parent_id'], ['id'])
    op.alter_column('incoming', '_purchase_cost',
               existing_type=sa.FLOAT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('incoming', '_persent',
               existing_type=sa.FLOAT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('incoming', '_cost_price',
               existing_type=sa.FLOAT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
